/*create table vid_categories_pay*/
CREATE TABLE IF NOT EXISTS vid_category_pays
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vid_category_pay VARCHAR(50) NOT NULL UNIQUE,
    CONSTRAINT pk_vid_category_pay PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS category_pays
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_pay VARCHAR(50) NOT NULL UNIQUE,
    vid_category_pay_id BIGINT NOT NULL,
    CONSTRAINT pk_category_pay PRIMARY KEY (id),
    CONSTRAINT category_pays_vid_category_pays_vid_category_pay_id FOREIGN KEY (vid_category_pay_id)
        REFERENCES vid_category_pays
);

CREATE TABLE IF NOT EXISTS pays
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pay         INT NOT NULL,
    category_pay_id BIGINT NOT NULL,
    time_pay    DATE NOT NULL,
    CONSTRAINT pk_pay PRIMARY KEY (id),
    CONSTRAINT pays_category_pays_category_pay_id FOREIGN KEY (category_pay_id) REFERENCES category_pays
);

CREATE TABLE IF NOT EXISTS period_pays
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    period_pay VARCHAR(50) NOT NULL UNIQUE,
    CONSTRAINT pk_period_pay PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS limit_pays
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_pay_id BIGINT NOT NULL,
    limit_pay       INT NOT NULL,
    period_pay_id   BIGINT NOT NULL,
    CONSTRAINT pk_limit PRIMARY KEY (id),
    CONSTRAINT limits_category_pays_category_pay_id FOREIGN KEY (category_pay_id) REFERENCES category_pays,
    CONSTRAINT limits_period_pays_period_pay_id FOREIGN KEY (period_pay_id) REFERENCES period_pays
);

CREATE TABLE IF NOT EXISTS vid_category_profits
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vid_category_profit VARCHAR(50) NOT NULL UNIQUE,
    CONSTRAINT pk_vid_category_profit PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS category_profits
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_profit VARCHAR(50) NOT NULL,
    vid_category_profit_id BIGINT NOT NULL,
    CONSTRAINT pk_category_profit PRIMARY KEY (id),
    CONSTRAINT caregory_profits_vid_category_profits_vid_category_profit_id FOREIGN KEY (vid_category_profit_id)
        REFERENCES vid_category_profits
    );

CREATE TABLE IF NOT EXISTS profits
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    profit         INT NOT NULL,
    category_profit_id BIGINT NOT NULL,
    time_profit    DATE NOT NULL,
    CONSTRAINT pk_profits PRIMARY KEY (id),
    CONSTRAINT profits_category_profits_category_profit_id FOREIGN KEY (category_profit_id)
        REFERENCES category_profits
    );